import {
  Activity,
  Building2,
  CalendarClock,
  CalendarRange,
  Clock,
  Database,
  FileJson,
  Fingerprint,
  Globe,
  Hash,
  IdCard,
  Key,
  KeyRound,
  Landmark,
  LayoutGrid,
  Link as LinkIcon,
  Lock,
  LucideIcon,
  Phone,
  Receipt,
  ShieldCheck,
  Type,
} from "lucide-react"

export interface ToolItem {
  slug: string;
  title: string;
  description: string;
  icon: LucideIcon;
  status: "new" | "hot" | "beta" | "coming-soon" | "stable";
  tags: string[];
  lastModified: string;
  related: string[];
}

export const TOOLS_CONFIG: ToolItem[] = [
  {
    slug: "uuid-generator",
    title: "UUID 生成器",
    description: "批量生成 UUID v1/v4，支援大小寫轉換與移除連字號，極速響應。",
    icon: Hash,
    status: "stable",
    tags: ["Generator", "GUID"],
    lastModified: "2026-04-01",
    related: ["hash-generator", "secret-generator"],
  },
  {
    slug: "base64-encoder",
    title: "Base64 編碼/解碼",
    description: "支援 UTF-8 中文的 Base64 轉換器，極速處理文字編解碼。",
    icon: Lock,
    status: "stable",
    tags: ["Encoder", "Security"],
    lastModified: "2026-04-01",
    related: ["url-encoder", "hash-generator"],
  },
  {
    slug: "json-formatter",
    title: "JSON 格式化/校驗",
    description: "美化 JSON 數據，語法高亮與錯誤檢測，支援壓縮模式。",
    icon: FileJson,
    status: "hot",
    tags: ["Formatter", "Dev"],
    lastModified: "2026-04-01",
    related: ["jwt-decoder", "url-encoder"],
  },
  {
    slug: "timestamp-converter",
    title: "Unix 時間戳轉換",
    description: "在 Unix Timestamp 與人類可讀日期之間互轉，支援秒/毫秒。",
    icon: Clock,
    status: "stable",
    tags: ["Converter", "Date"],
    lastModified: "2026-04-01",
    related: ["timezone-converter", "cron-calculator"],
  },
  {
    slug: "timezone-converter",
    title: "時區轉換/偏移",
    description: "UTC 與本地時間即時對照，支援時間偏移 (Offset) 模擬測試。",
    icon: Globe,
    status: "stable",
    tags: ["Timezone", "ISO"],
    lastModified: "2026-04-01",
    related: ["timestamp-converter", "cron-calculator"],
  },
  {
    slug: "url-encoder",
    title: "URL 編碼/解碼",
    description: "將 URL 特殊字符轉換為百分號編碼，確保參數傳輸安全。",
    icon: LinkIcon,
    status: "stable",
    tags: ["Encoder", "Web"],
    lastModified: "2026-04-01",
    related: ["base64-encoder", "json-formatter"],
  },
  {
    slug: "sql-formatter",
    title: "SQL 格式化工具",
    description: "美化複雜的 SQL 查詢語句，支援多種資料庫方言 (MySQL, PG)。",
    icon: Database,
    status: "coming-soon",
    tags: ["Formatter", "DB"],
    lastModified: "2026-04-01",
    related: ["json-formatter"],
  },
  {
    slug: "hash-generator",
    title: "Hash 雜湊生成器",
    description: "計算文字的 MD5, SHA-1, SHA-256 雜湊值 (Client-side Only)。",
    icon: ShieldCheck,
    status: "stable",
    tags: ["Security", "Crypto"],
    lastModified: "2026-04-01",
    related: ["base64-encoder", "secret-generator"],
  },
  {
    slug: "lorem-ipsum",
    title: "假文產生器",
    description: "生成 Lorem Ipsum 假文、中文假文、數字資料與模擬訂單，排版與測試資料好幫手。",
    icon: Type,
    status: "hot",
    tags: ["Generator", "Design", "Mock Data"],
    lastModified: "2026-07-03",
    related: ["uuid-generator"],
  },
  {
    slug: "jwt-decoder",
    title: "JWT 解碼器",
    description: "解析 JWT Token 結構 (Header, Payload)，除錯身份驗證問題。",
    icon: KeyRound,
    status: "new",
    tags: ["Auth", "Security"],
    lastModified: "2026-04-20",
    related: ["jwt-encoder", "secret-generator"],
  },
  {
    slug: "jwt-encoder",
    title: "JWT 生成器",
    description: "自訂 Payload 並簽署 JWT Token，方便測試 API 權限。",
    icon: Key,
    status: "new",
    tags: ["Auth", "Generator"],
    lastModified: "2026-04-20",
    related: ["jwt-decoder", "secret-generator"],
  },
  {
    slug: "secret-generator",
    title: "Secret 生成器",
    description: "安全產生 JWT Secret、API Key、隨機密碼與 AES 金鑰，純瀏覽器端執行。",
    icon: Fingerprint,
    status: "new",
    tags: ["Security", "Generator"],
    lastModified: "2026-05-07",
    related: ["jwt-decoder", "jwt-encoder", "hash-generator"],
  },
  {
    slug: "cron-calculator",
    title: "Cron 表達式計算器",
    description: "驗證 Crontab 語法、翻譯成中文說明，並計算下次執行時間，DevOps 排程好幫手。",
    icon: CalendarClock,
    status: "new",
    tags: ["DevOps", "Scheduler"],
    lastModified: "2026-07-03",
    related: ["timestamp-converter", "timezone-converter"],
  },
  {
    slug: "ubn-validator",
    title: "統一編號檢查碼驗證器",
    description: "驗證公司統一編號檢查碼是否正確，支援 2021 年新制除以 5 邏輯，並可產生測試用合法編號。",
    icon: Building2,
    status: "new",
    tags: ["Taiwan", "Validator"],
    lastModified: "2026-07-03",
    related: ["id-number-validator", "invoice-validator"],
  },
  {
    slug: "id-number-validator",
    title: "身分證字號驗證器",
    description: "依官方檢查碼公式即時驗證身分證字號格式是否正確，純瀏覽器端運算。",
    icon: IdCard,
    status: "new",
    tags: ["Taiwan", "Validator"],
    lastModified: "2026-07-03",
    related: ["ubn-validator", "roc-year-converter"],
  },
  {
    slug: "roc-year-converter",
    title: "民國年/西元年互轉",
    description: "輸入民國或西元年月日，即時雙向換算，填寫政府表單、核對證件日期必備。",
    icon: CalendarRange,
    status: "new",
    tags: ["Taiwan", "Date"],
    lastModified: "2026-07-03",
    related: ["timestamp-converter", "id-number-validator"],
  },
  {
    slug: "phone-validator",
    title: "手機/市話格式驗證",
    description: "自動判斷手機門號或市話，並檢查區碼與位數是否符合台灣電信編碼規則。",
    icon: Phone,
    status: "new",
    tags: ["Taiwan", "Validator"],
    lastModified: "2026-07-03",
    related: ["bank-code-lookup", "id-number-validator"],
  },
  {
    slug: "invoice-validator",
    title: "統一發票號碼格式驗證",
    description: "檢查統一發票號碼是否符合 2 碼英文字軌 + 8 碼數字的標準格式。",
    icon: Receipt,
    status: "new",
    tags: ["Taiwan", "Validator"],
    lastModified: "2026-07-03",
    related: ["ubn-validator", "bank-code-lookup"],
  },
  {
    slug: "bank-code-lookup",
    title: "銀行代碼/金融機構查詢",
    description: "輸入銀行名稱或代碼，快速查詢台灣常見金融機構 3 碼代號對照表。",
    icon: Landmark,
    status: "new",
    tags: ["Taiwan", "Finance"],
    lastModified: "2026-07-03",
    related: ["invoice-validator", "phone-validator"],
  },
  {
    slug: "bmi-calculator",
    title: "BMI計算機（含兵役體位標準）",
    description: "輸入身高體重即時算出 BMI，並對照 WHO 分級與兵役體位 BMI 門檻參考值。",
    icon: Activity,
    status: "new",
    tags: ["Health", "Taiwan"],
    lastModified: "2026-07-03",
    related: ["id-number-validator", "roc-year-converter"],
  },
];

export const NAV_ITEMS = [
  {
    label: "導航大廳",
    icon: LayoutGrid,
    href: "/",
    color: "text-sky-500",
  },
];
